package certificates

import "github.com/sirupsen/logrus"

type StrategiesParams struct {
	Domain     string
	CommonName string
	BasePath   string

	CertificatePath    string
	CertificateKeyPath string

	Log *logrus.Entry
}

func GetStrategy(name string, params StrategiesParams) CertificateAuthority {
	strategies := map[string]CertificateAuthority{
		Autogenerated: &AutoGenerateStrategy{
			Log:        params.Log,
			Domain:     params.Domain,
			CommonName: params.CommonName,
			BasePath:   params.BasePath,
		},
		Custom: &CustomStrategy{
			CertificatePath:    params.CertificatePath,
			CertificateKeyPath: params.CertificateKeyPath,
		},
		Noop: &NoopStrategy{},
	}

	if str, ok := strategies[name]; ok {
		return str
	}

	return strategies[Noop]
}
